@startuml
(*)  --> "check input"
If "input is verbose" then
--> [Yes] "turn on verbosity"
--> "run command"
else
--> "run command"
Endif
-->(*)

@enduml

@startuml
(*) --> (*)


"utils.h" --> "Heap.h"

"IndexFlat.h" --> "Index.h"
"ProductQuantizer.h" --> "Clustering.h"

"ProductQuantizer.h" --> "Heap.h"

"Clustering.h" --> "Index.h"
"VectorTransform.h" --> "Index.h"

"PolysemousTraining.h" --> "ProductQuantizer.h"
"IndexIVFPQ.h" --> "IndexIVF.h"
"IndexIVFPQ.h" --> "IndexPQ.h"
"AuxIndexStructures.h" --> "Index.h"
"hamming.h" --> "Heap.h"
"IndexPQ.h" --> "Index.h"
"IndexPQ.h" --> "ProductQuantizer.h"
"IndexPQ.h" --> "PolysemousTraining.h"
"AutoTune.h" --> "Index.h"
"IndexIVF.h" --> "Index.h"
"IndexIVF.h" --> "Clustering.h"

"IndexIVF.h" --> "Heap.h"
"FaissAssert.h" --> "FaissException.h"
"IndexLSH.h" --> "Index.h"
"IndexLSH.h" --> "VectorTransform.h"
"IndexScalarQuantizer.h" --> "IndexIVF.h"
"MetaIndexes.h" --> "Index.h"
"SpectraST_mzParser.h" --> "expat.h"
"SpectraST_mzParser.h" --> "zlib.h"
"SpectraST_mzParser.h" --> "SpectraST_MSNumpress.hpp"
"SpectraST_mzParser.h" --> "hdf5.h"
"SpectraST_mzParser.h" --> "H5Cpp.h"
"SpectraST_kwset.h" --> "SpectraST_obstack.h"
"SpectraST_ramp.h" --> "sysdepend.h"
"SpectraST_ramp.h" --> "random_access_gzFile.h"
"SpectraST_ramp.h" --> "SpectraST_base64.h"
"predicted_spectra.h" --> "AllScoreModels.h"
"swathdenoise.h" --> "PeakList.h"
"CWorkFlow.h" --> "Parameters.h"
"CWorkFlow.h" --> "BasicFunction.h"
"CWorkFlow.h" --> "MS1Reader.h"
"Predictor.h" --> "Parameters.h"
"Predictor.h" --> "Clog.h"
"Predictor.h" --> "BasicFunction.h"
"MS1Spectrum.h" --> "BasicFunction.h"
"MS1Spectrum.h" --> "CentroidPeaks.h"
"BasicFunction.h" --> "Clog.h"
"BasicFunction.h" --> "CPFReader.h"
"BasicFunction.h" --> "Parameters.h"
"MS2Spectrum.h" --> "BasicFunction.h"
"MS2Spectrum.h" --> "CentroidPeaks.h"
"Com.h" --> "CentroidPeaks.h"
"Com.h" --> "BasicFunction.h"
"MS2Reader.h" --> "Parameters.h"
"MS2Reader.h" --> "MS2Spectrum.h"
"MS1Reader.h" --> "Parameters.h"
"MS1Reader.h" --> "MS1Spectrum.h"
"MS1Reader.h" --> "TrainingFileReader.h"
"MS1Reader.h" --> "MS2Reader.h"
"MS1Reader.h" --> "CpParseDebug.h"
"MS1Reader.h" --> "Predictor.h"
"MS1Reader.h" --> "mars.h"
"MS1Reader.h" --> "CPeakMap.h"
"MS1Reader.h" --> "IPVCalc.h"
"MS1Reader.h" --> "CalcFeature.h"
"MS1Reader.h" --> "MS1Reader.h"
"MS1Reader.h" --> "MS1Reader.h"
"PSMScoreCalculator.h" --> "PeakPairScore.h"
"PSMScoreCalculator.h" --> "CPeakPair.h"
"CPeakPairsImporter.h" --> "CPeakPair.h"
"CPeakPairsImporter.h" --> "MGFReader.h"
"CPeakPairsImporter.h" --> "linear.h"
"PeakInfo.h" --> "peak_annotation.h"
"ConcretePSMFeatures.h" --> "BasePSMFeature.h"
"ConcretePSMFeatures.h" --> "MGFReader.h"
"ConcretePSMFeatures.h" --> "CPeakPair.h"
"ConcretePSMFeatures.h" --> "CPeakPairsImporter.h"
"ConcretePSMFeatures.h" --> "classifier.h"
"ConcretePSMFeatures.h" --> "FragmentationScore.h"
"CFragScore.h" --> "PeakPairScore.h"
"CFlow.h" --> "CPeakPairsImporter.h"
"CFlow.h" --> "spdlog.h"
"CFlow.h" --> "ProteomicsDataTypes.h"
"CFlow.h" --> "ConcretePSMFeatures.h"
"CFlow.h" --> "CDebugMode.h"
"CFlow.h" --> "Util.h"
"BasePSMFeature.h" --> "predicted_spectra.h"
"BasePSMFeature.h" --> "SpectraSTPeakList.hpp"
"BasePSMFeature.h" --> "Peptide.hpp"
"BasePSMFeature.h" --> "FileUtils.hpp"
"classifier.h" --> "CPeakPairsImporter.h"
"classifier.h" --> "CFragScore.h"
"classifier.h" --> "linear.h"
"MGFReader.h" --> "SpectraSTPeakList.hpp"
"MGFReader.h" --> "BasePSMFeature.h"
"MGFReader.h" --> "Util.h"
"MGFReader.h" --> "PeakInfo.h"
"MGFReader.h" --> "peak_annotation.h"
"MGFReader.h" --> "XMLFileParser.h"
"MGFReader.h" --> "CPeakPair.h"
"gnuplot_functions.h" --> "gnuplot-iostream.h"
"liblinearWrapper.h" --> "linear.h"
"FragmentationScore.h" --> "CFragScore.h"
"FragmentationScore.h" --> "PSMScoreCalculator.h"
"FragmentationScore.h" --> "CPeakPairsImporter.h"
"FragmentationScore.h" --> "classifier.h"
"SpectraST_kwset.h" --> "SpectraST_obstack.h"
"SpectraST_ramp.h" --> "sysdepend.h"
"SpectraST_ramp.h" --> "random_access_gzFile.h"
"SpectraST_ramp.h" --> "SpectraST_base64.h"
"MARSModel.h" --> "BasicFunction.h"
"mzXMLReader.h" --> "SpectraST_cramp.hpp"
"mzXMLReader.h" --> "PeakList.h"
"mzXMLReader.h" --> "Util.h"
"ICMzFile.h" --> "ProteomicsDataTypes.h"
"CMzFileReader.h" --> "ProteomicsDataTypes.h"
"CMzFileReader.h" --> "ICMzFile.h"
"PeakList.h" --> "Util.h"
"SpectraST_ramp.h" --> "sysdepend.h"
"SpectraST_ramp.h" --> "random_access_gzFile.h"
"SpectraST_ramp.h" --> "SpectraST_base64.h"
"Util.h" --> "PeakList.h"
"Util.h" --> "spdlog.h"
"DatabaseManager.h" --> "Util.h"
"XMLFileParser.h" --> "rapidxml.hpp"
"XMLFileParser.h" --> "rapidxml_print.hpp"
"XMLFileParser.h" --> "Util.h"
"XMLFileParser.h" --> "ProteomicsDataTypes.h"
"SWATHmzXMLReader.h" --> "mzXMLReader.h"
"ProteomicsDataTypes.h" --> "XMLFileParser.h"

@enduml

@startuml
(*)-->(*)
"utils.h" --> "Heap.h"
"IndexFlat.h" --> "Index.h"
"ProductQuantizer.h" --> "Clustering.h"
"ProductQuantizer.h" --> "Heap.h"
"Clustering.h" --> "Index.h"
"VectorTransform.h" --> "Index.h"
"PolysemousTraining.h" --> "ProductQuantizer.h"
"IndexIVFPQ.h" --> "IndexIVF.h"
"IndexIVFPQ.h" --> "IndexPQ.h"
"AuxIndexStructures.h" --> "Index.h"
"hamming.h" --> "Heap.h"
"IndexPQ.h" --> "Index.h"
"IndexPQ.h" --> "ProductQuantizer.h"
"IndexPQ.h" --> "PolysemousTraining.h"
"AutoTune.h" --> "Index.h"
"IndexIVF.h" --> "Index.h"
"IndexIVF.h" --> "Clustering.h"
"IndexIVF.h" --> "Heap.h"
"FaissAssert.h" --> "FaissException.h"
"IndexLSH.h" --> "Index.h"
"IndexLSH.h" --> "VectorTransform.h"
"IndexScalarQuantizer.h" --> "IndexIVF.h"
"MetaIndexes.h" --> "Index.h"
"SpectraST_mzParser.h" --> "expat.h"
"SpectraST_mzParser.h" --> "zlib.h"
"SpectraST_mzParser.h" --> "SpectraST_MSNumpress.hpp"
"SpectraST_mzParser.h" --> "hdf5.h"
"SpectraST_mzParser.h" --> "H5Cpp.h"
"SpectraST_kwset.h" --> "SpectraST_obstack.h"
"SpectraST_ramp.h" --> "sysdepend.h"
"SpectraST_ramp.h" --> "random_access_gzFile.h"
"SpectraST_ramp.h" --> "SpectraST_base64.h"
"predicted_spectra.h" --> "AllScoreModels.h"
"swathdenoise.h" --> "PeakList.h"
"CWorkFlow.h" --> "Parameters.h"
"CWorkFlow.h" --> "BasicFunction.h"
"CWorkFlow.h" --> "MS1Reader.h"
"Predictor.h" --> "Parameters.h"
"Predictor.h" --> "Clog.h"
"Predictor.h" --> "BasicFunction.h"
"MS1Spectrum.h" --> "BasicFunction.h"
"BasicFunction.h" --> "Clog.h"
"BasicFunction.h" --> "CPFReader.h"
"BasicFunction.h" --> "Parameters.h"
"MS2Spectrum.h" --> "BasicFunction.h"
"Com.h" --> "BasicFunction.h"
"MS2Reader.h" --> "Parameters.h"
"MS2Reader.h" --> "MS2Spectrum.h"
"MS1Reader.h" --> "Parameters.h"
"MS1Reader.h" --> "MS1Spectrum.h"
"MS1Reader.h" --> "TrainingFileReader.h"
"MS1Reader.h" --> "MS2Reader.h"
"MS1Reader.h" --> "CpParseDebug.h"
"MS1Reader.h" --> "Predictor.h"
"MS1Reader.h" --> "mars.h"
"MS1Reader.h" --> "CPeakMap.h"
"MS1Reader.h" --> "IPVCalc.h"
"PSMScoreCalculator.h" --> "PeakPairScore.h"
"PSMScoreCalculator.h" --> "CPeakPair.h"
"CPeakPairsImporter.h" --> "CPeakPair.h"
"CPeakPairsImporter.h" --> "MGFReader.h"
"CPeakPairsImporter.h" --> "linear.h"
"PeakInfo.h" --> "peak_annotation.h"
"ConcretePSMFeatures.h" --> "BasePSMFeature.h"
"ConcretePSMFeatures.h" --> "MGFReader.h"
"ConcretePSMFeatures.h" --> "CPeakPair.h"
"ConcretePSMFeatures.h" --> "CPeakPairsImporter.h"
"ConcretePSMFeatures.h" --> "classifier.h"
"ConcretePSMFeatures.h" --> "FragmentationScore.h"
"CFragScore.h" --> "PeakPairScore.h"
"CFlow.h" --> "CPeakPairsImporter.h"
"CFlow.h" --> "ProteomicsDataTypes.h"
"CFlow.h" --> "ConcretePSMFeatures.h"
"CFlow.h" --> "CDebugMode.h"
"CFlow.h" --> "Util.h"
"BasePSMFeature.h" --> "predicted_spectra.h"
"BasePSMFeature.h" --> "SpectraSTPeakList.hpp"
"BasePSMFeature.h" --> "Peptide.hpp"
"BasePSMFeature.h" --> "FileUtils.hpp"
"classifier.h" --> "CPeakPairsImporter.h"
"classifier.h" --> "CFragScore.h"
"classifier.h" --> "linear.h"
"MGFReader.h" --> "SpectraSTPeakList.hpp"
"MGFReader.h" --> "BasePSMFeature.h"
"MGFReader.h" --> "Util.h"
"MGFReader.h" --> "PeakInfo.h"
"MGFReader.h" --> "peak_annotation.h"
"MGFReader.h" --> "XMLFileParser.h"
"MGFReader.h" --> "CPeakPair.h"
"gnuplot_functions.h" --> "gnuplot-iostream.h"
"liblinearWrapper.h" --> "linear.h"
"FragmentationScore.h" --> "CFragScore.h"
"FragmentationScore.h" --> "PSMScoreCalculator.h"
"FragmentationScore.h" --> "CPeakPairsImporter.h"
"FragmentationScore.h" --> "classifier.h"
"SpectraST_kwset.h" --> "SpectraST_obstack.h"
"SpectraST_ramp.h" --> "sysdepend.h"
"SpectraST_ramp.h" --> "random_access_gzFile.h"
"SpectraST_ramp.h" --> "SpectraST_base64.h"
"MARSModel.h" --> "BasicFunction.h"
"MARSModel.h" --> "Dense"
"CMzFileReader.h" --> "ICMzFile.h"
"CMzFileReader.h" --> "ICQuery.h"
"ICQuery.h" --> "ProteomicsDataTypes.h"
"mzXMLReader.h" --> "SpectraST_cramp.hpp"
"mzXMLReader.h" --> "PeakList.h"
"mzXMLReader.h" --> "Util.h"
"ICMzFile.h" --> "ICQuery.h"
"CArchiveSearchReply.h" --> "CAnnotationDB.h"
"CArchiveSearchReply.h" --> "Util.h"
"CFragmentIndex.h" --> "CMzFileReader.h"
"GtUpdator.h" --> "DatabaseManager.h"
"GtUpdator.h" --> "XMLFileParser.h"
"SpectraST_ramp.h" --> "sysdepend.h"
"SpectraST_ramp.h" --> "random_access_gzFile.h"
"SpectraST_ramp.h" --> "SpectraST_base64.h"
"Util.h" --> "PeakList.h"
"GraphKNN.h" --> "Util.h"
"DatabaseManager.h" --> "Util.h"
"ConcreteQueries.h" --> "ICQuery.h"
"ConcreteQueries.h" --> "ICMzFile.h"
"XMLFileParser.h" --> "rapidxml.hpp"
"XMLFileParser.h" --> "rapidxml_print.hpp"
"XMLFileParser.h" --> "Util.h"
"SWATHmzXMLReader.h" --> "mzXMLReader.h"
"ProteomicsDataTypes.h" --> "XMLFileParser.h"
"CAnnotationDB.h" --> "DatabaseManager.h"
"CAnnotationDB.h" --> "ProteomicsDataTypes.h"
"dpcuda.h" --> "ICMzFile.h"
"dpcuda.h" --> "ICQuery.h"
"CKMeans.h" --> "Core"
"CKMeans.h" --> "Dense"
"CMultiIndices.h" --> "CKMeans.h"
"pvalueCalc.h" --> "CFragmentIndex.h"
"pvalueCalc.h" --> "ConcreteQueries.h"
"pvalueCalc.h" --> "CArchiveSearchReply.h"
"LibSearchEngine.h" --> "ProteomicsDataTypes.h"
"CLinearRegression.h" --> "Core"
"CLinearRegression.h" --> "Dense"
"CSpectralArchive.h" --> "CArchiveSearchReply.h"
"ICIndexWrapper.h" --> "CKMeans.h"
"CMyIndex.h" --> "ICIndexWrapper.h"
"CMyIndex.h" --> "CKMeans.h"
"CSocketServer.h" --> "Util.h"
"CSocketServer.h" --> "CSpectralArchive.h"
"CTailEstimation.h" --> "gnuplot-iostream.h"
"CFaissIndex.h" --> "ICIndexWrapper.h"
"Visual.h" --> "gnuplot-iostream.h"
"plotUtilities.h" --> "gnuplot-iostream.h"
"EMAlgorithm.h" --> "Util.h"
"EMAlgorithm.h" --> "Visual.h"
"FCgiIO.h" --> "fcgio.h"
"FCgiIO.h" --> "CgiInput.h"
@enduml