@startuml
(*) --> (*)
"predicted_spectra.h"  --> "AllScoreModels.h"
"dpcuda.h"  --> "ICMzFile.h"
"CLinearRegression.h"  --> "Core"
"CLinearRegression.h"  --> "Dense"
"CKMeans.h"  --> "Core"
"CKMeans.h"  --> "Dense"
"utils.h"  --> "Heap.h"
"MS1Reader.h"  --> "Parameters.h"
"MS1Reader.h"  --> "MS1Spectrum.h"
"MS1Reader.h"  --> "TrainingFileReader.h"
"MS1Reader.h"  --> "MS2Reader.h"
"MS1Reader.h"  --> "CpParseDebug.h"
"MS1Reader.h"  --> "Predictor.h"
"MS1Reader.h"  --> "mars.h"
"MS1Reader.h"  --> "CPeakMap.h"
"MS1Reader.h"  --> "IPVCalc.h"
"SWATHmzXMLReader.h"  --> "mzXMLReader.h"
"IndexPQ.h"  --> "Index.h"
"IndexPQ.h"  --> "ProductQuantizer.h"
"IndexPQ.h"  --> "PolysemousTraining.h"
"VectorTransform.h"  --> "Index.h"
"MS1Spectrum.h"  --> "BasicFunction.h"
"XMLFileParser.h"  --> "rapidxml.hpp"
"XMLFileParser.h"  --> "ICGtInfoUpdate.h"
"MetaIndexes.h"  --> "Index.h"
"MS2Spectrum.h"  --> "BasicFunction.h"
"SpectraST_ramp.h"  --> "sysdepend.h"
"SpectraST_ramp.h"  --> "random_access_gzFile.h"
"SpectraST_ramp.h"  --> "SpectraST_base64.h"
"SpectraST_ramp.h"  --> "sysdepend.h"
"SpectraST_ramp.h"  --> "random_access_gzFile.h"
"SpectraST_ramp.h"  --> "SpectraST_base64.h"
"PolysemousTraining.h"  --> "ProductQuantizer.h"
"Com.h"  --> "BasicFunction.h"
"Clustering.h"  --> "Index.h"
"IndexIVF.h"  --> "Index.h"
"IndexIVF.h"  --> "Clustering.h"
"IndexIVF.h"  --> "Heap.h"
"IndexIVFPQ.h"  --> "IndexIVF.h"
"IndexIVFPQ.h"  --> "IndexPQ.h"
"swathdenoise.h"  --> "PeakList.h"
"ConcreteQueries.h"  --> "ICQuery.h"
"CFaissIndex.h"  --> "ICIndexWrapper.h"
"EMAlgorithm.h"  --> "Util.h"
"EMAlgorithm.h"  --> "Visual.h"
"SpectraST_kwset.h"  --> "SpectraST_obstack.h"
"MS2Reader.h"  --> "Parameters.h"
"MS2Reader.h"  --> "MS2Spectrum.h"
"Predictor.h"  --> "Parameters.h"
"Predictor.h"  --> "Clog.h"
"Predictor.h"  --> "BasicFunction.h"
"SpectraST_mzParser.h"  --> "expat.h"
"SpectraST_mzParser.h"  --> "zlib.h"
"SpectraST_mzParser.h"  --> "SpectraST_MSNumpress.hpp"
"SpectraST_mzParser.h"  --> "hdf5.h"
"SpectraST_mzParser.h"  --> "H5Cpp.h"
"AutoTune.h"  --> "Index.h"
"IndexFlat.h"  --> "Index.h"
"BasicFunction.h"  --> "Clog.h"
"BasicFunction.h"  --> "CPFReader.h"
"BasicFunction.h"  --> "Parameters.h"
"CMzFileReader.h"  --> "ICMzFile.h"
"CMzFileReader.h"  --> "ICQuery.h"
"CMzFileReader.h"  --> "XMLFileParser.h"
"CMyIndex.h"  --> "ICIndexWrapper.h"
"IndexScalarQuantizer.h"  --> "IndexIVF.h"
"FaissAssert.h"  --> "FaissException.h"
"SpectraST_kwset.h"  --> "SpectraST_obstack.h"
"IndexLSH.h"  --> "Index.h"
"IndexLSH.h"  --> "VectorTransform.h"
"ProductQuantizer.h"  --> "Clustering.h"
"ProductQuantizer.h"  --> "Heap.h"
"FCgiIO.h"  --> "fcgio.h"
"FCgiIO.h"  --> "CgiInput.h"
"hamming.h"  --> "Heap.h"
"SpectraST_ramp.h"  --> "sysdepend.h"
"SpectraST_ramp.h"  --> "random_access_gzFile.h"
"SpectraST_ramp.h"  --> "SpectraST_base64.h"
"AuxIndexStructures.h"  --> "Index.h"
"CWorkFlow.h"  --> "Parameters.h"
"CWorkFlow.h"  --> "BasicFunction.h"
"CWorkFlow.h"  --> "MS1Reader.h"
"MARSModel.h"  --> "BasicFunction.h"
"MARSModel.h"  --> "Dense"
"Visual.cpp" #99FF99 --> "Visual.h"
"Visual.cpp" #99FF99 --> "gnuplot-iostream.h"
@enduml